<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260420123708 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE images (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, posted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E01FBE6A5A6D2235 ON images (posted_by_id)');
        $this->addSql('CREATE TABLE matches (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score1 INT DEFAULT NULL, score2 INT DEFAULT NULL, round INT NOT NULL, player1_id INT DEFAULT NULL, player2_id INT DEFAULT NULL, tournament_id INT NOT NULL, winner_id INT DEFAULT NULL, next_match_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_62615BAC0990423 ON matches (player1_id)');
        $this->addSql('CREATE INDEX IDX_62615BAD22CABCD ON matches (player2_id)');
        $this->addSql('CREATE INDEX IDX_62615BA33D1A3E7 ON matches (tournament_id)');
        $this->addSql('CREATE INDEX IDX_62615BA5DFCD4B8 ON matches (winner_id)');
        $this->addSql('CREATE INDEX IDX_62615BA12A4E038 ON matches (next_match_id)');
        $this->addSql('CREATE TABLE registered (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, seed INT DEFAULT NULL, user_id INT NOT NULL, tournament_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4BFEE160A76ED395 ON registered (user_id)');
        $this->addSql('CREATE INDEX IDX_4BFEE16033D1A3E7 ON registered (tournament_id)');
        $this->addSql('CREATE TABLE reset_password_requests (rpr_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, rpr_usr_id INT NOT NULL, PRIMARY KEY (rpr_id))');
        $this->addSql('CREATE INDEX IDX_16646B4167D683ED ON reset_password_requests (rpr_usr_id)');
        $this->addSql('CREATE TABLE tournament (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, date DATE NOT NULL, price DOUBLE PRECISION DEFAULT NULL, max_nb INT DEFAULT NULL, banner VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, discipline VARCHAR(255) NOT NULL, mail VARCHAR(255) NOT NULL, end_date DATE NOT NULL, description TEXT DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, is_started BOOLEAN NOT NULL, location_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BD5FB8D964D218E ON tournament (location_id)');
        $this->addSql('CREATE INDEX IDX_BD5FB8D9B03A8386 ON tournament (created_by_id)');
        $this->addSql('CREATE TABLE town (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, postalcode VARCHAR(5) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, roles JSON NOT NULL, firstname VARCHAR(160) NOT NULL, lastname VARCHAR(160) NOT NULL, pseudo VARCHAR(160) NOT NULL, mail VARCHAR(160) NOT NULL, address VARCHAR(160) NOT NULL, profile_pic VARCHAR(255) DEFAULT NULL, birthdate DATE NOT NULL, registered_at DATE NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE images ADD CONSTRAINT FK_E01FBE6A5A6D2235 FOREIGN KEY (posted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT FK_62615BAC0990423 FOREIGN KEY (player1_id) REFERENCES registered (id)');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT FK_62615BAD22CABCD FOREIGN KEY (player2_id) REFERENCES registered (id)');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT FK_62615BA33D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT FK_62615BA5DFCD4B8 FOREIGN KEY (winner_id) REFERENCES registered (id)');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT FK_62615BA12A4E038 FOREIGN KEY (next_match_id) REFERENCES matches (id)');
        $this->addSql('ALTER TABLE registered ADD CONSTRAINT FK_4BFEE160A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE registered ADD CONSTRAINT FK_4BFEE16033D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reset_password_requests ADD CONSTRAINT FK_16646B4167D683ED FOREIGN KEY (rpr_usr_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tournament ADD CONSTRAINT FK_BD5FB8D964D218E FOREIGN KEY (location_id) REFERENCES town (id)');
        $this->addSql('ALTER TABLE tournament ADD CONSTRAINT FK_BD5FB8D9B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE images DROP CONSTRAINT FK_E01FBE6A5A6D2235');
        $this->addSql('ALTER TABLE matches DROP CONSTRAINT FK_62615BAC0990423');
        $this->addSql('ALTER TABLE matches DROP CONSTRAINT FK_62615BAD22CABCD');
        $this->addSql('ALTER TABLE matches DROP CONSTRAINT FK_62615BA33D1A3E7');
        $this->addSql('ALTER TABLE matches DROP CONSTRAINT FK_62615BA5DFCD4B8');
        $this->addSql('ALTER TABLE matches DROP CONSTRAINT FK_62615BA12A4E038');
        $this->addSql('ALTER TABLE registered DROP CONSTRAINT FK_4BFEE160A76ED395');
        $this->addSql('ALTER TABLE registered DROP CONSTRAINT FK_4BFEE16033D1A3E7');
        $this->addSql('ALTER TABLE reset_password_requests DROP CONSTRAINT FK_16646B4167D683ED');
        $this->addSql('ALTER TABLE tournament DROP CONSTRAINT FK_BD5FB8D964D218E');
        $this->addSql('ALTER TABLE tournament DROP CONSTRAINT FK_BD5FB8D9B03A8386');
        $this->addSql('DROP TABLE images');
        $this->addSql('DROP TABLE matches');
        $this->addSql('DROP TABLE registered');
        $this->addSql('DROP TABLE reset_password_requests');
        $this->addSql('DROP TABLE tournament');
        $this->addSql('DROP TABLE town');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
