<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414080527 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE images (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, posted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E01FBE6A5A6D2235 ON images (posted_by_id)');
        $this->addSql('CREATE TABLE registered (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, user_id INT NOT NULL, tournament_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4BFEE160A76ED395 ON registered (user_id)');
        $this->addSql('CREATE INDEX IDX_4BFEE16033D1A3E7 ON registered (tournament_id)');
        $this->addSql('CREATE TABLE tournament (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, date DATE NOT NULL, price DOUBLE PRECISION DEFAULT NULL, max_nb INT DEFAULT NULL, banner VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE town (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, postalcode VARCHAR(5) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname VARCHAR(160) NOT NULL, lastname VARCHAR(160) NOT NULL, pseudo VARCHAR(160) NOT NULL, mail VARCHAR(160) NOT NULL, address VARCHAR(160) NOT NULL, profile_pic VARCHAR(255) DEFAULT NULL, birthdate DATE NOT NULL, registered_at DATE NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE images ADD CONSTRAINT FK_E01FBE6A5A6D2235 FOREIGN KEY (posted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE registered ADD CONSTRAINT FK_4BFEE160A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE registered ADD CONSTRAINT FK_4BFEE16033D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE images DROP CONSTRAINT FK_E01FBE6A5A6D2235');
        $this->addSql('ALTER TABLE registered DROP CONSTRAINT FK_4BFEE160A76ED395');
        $this->addSql('ALTER TABLE registered DROP CONSTRAINT FK_4BFEE16033D1A3E7');
        $this->addSql('DROP TABLE images');
        $this->addSql('DROP TABLE registered');
        $this->addSql('DROP TABLE tournament');
        $this->addSql('DROP TABLE town');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
