<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260420183917 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE images (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, posted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_e01fbe6a5a6d2235 ON images (posted_by_id)');
        $this->addSql('ALTER TABLE images ADD CONSTRAINT fk_e01fbe6a5a6d2235 FOREIGN KEY (posted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE matches (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score1 INT DEFAULT NULL, score2 INT DEFAULT NULL, round INT NOT NULL, player1_id INT DEFAULT NULL, player2_id INT DEFAULT NULL, tournament_id INT NOT NULL, winner_id INT DEFAULT NULL, next_match_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_62615ba33d1a3e7 ON matches (tournament_id)');
        $this->addSql('CREATE INDEX idx_62615ba5dfcd4b8 ON matches (winner_id)');
        $this->addSql('CREATE INDEX idx_62615ba12a4e038 ON matches (next_match_id)');
        $this->addSql('CREATE INDEX idx_62615bac0990423 ON matches (player1_id)');
        $this->addSql('CREATE INDEX idx_62615bad22cabcd ON matches (player2_id)');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT fk_62615ba5dfcd4b8 FOREIGN KEY (winner_id) REFERENCES registered (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT fk_62615ba33d1a3e7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT fk_62615bad22cabcd FOREIGN KEY (player2_id) REFERENCES registered (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT fk_62615bac0990423 FOREIGN KEY (player1_id) REFERENCES registered (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT fk_62615ba12a4e038 FOREIGN KEY (next_match_id) REFERENCES matches (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE registered (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, user_id INT NOT NULL, tournament_id INT NOT NULL, seed INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_4bfee160a76ed395 ON registered (user_id)');
        $this->addSql('CREATE INDEX idx_4bfee16033d1a3e7 ON registered (tournament_id)');
        $this->addSql('ALTER TABLE registered ADD CONSTRAINT fk_4bfee16033d1a3e7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE registered ADD CONSTRAINT fk_4bfee160a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE reset_password_requests (rpr_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, rpr_usr_id INT NOT NULL, PRIMARY KEY (rpr_id))');
        $this->addSql('CREATE INDEX idx_16646b4167d683ed ON reset_password_requests (rpr_usr_id)');
        $this->addSql('ALTER TABLE reset_password_requests ADD CONSTRAINT fk_16646b4167d683ed FOREIGN KEY (rpr_usr_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE tournament (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, date DATE NOT NULL, price DOUBLE PRECISION DEFAULT NULL, max_nb INT DEFAULT NULL, banner VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, location_id INT DEFAULT NULL, discipline VARCHAR(255) NOT NULL, mail VARCHAR(255) NOT NULL, end_date DATE NOT NULL, description TEXT DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, created_by_id INT DEFAULT NULL, is_started BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_bd5fb8d9b03a8386 ON tournament (created_by_id)');
        $this->addSql('CREATE INDEX idx_bd5fb8d964d218e ON tournament (location_id)');
        $this->addSql('ALTER TABLE tournament ADD CONSTRAINT fk_bd5fb8d9b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament ADD CONSTRAINT fk_bd5fb8d964d218e FOREIGN KEY (location_id) REFERENCES town (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE town (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, postalcode VARCHAR(5) NOT NULL, PRIMARY KEY (id))');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname VARCHAR(160) NOT NULL, lastname VARCHAR(160) NOT NULL, pseudo VARCHAR(160) NOT NULL, mail VARCHAR(160) NOT NULL, address VARCHAR(160) NOT NULL, profile_pic VARCHAR(255) DEFAULT NULL, birthdate DATE NOT NULL, registered_at DATE NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "images"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "matches"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "messenger_messages"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "registered"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "reset_password_requests"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "tournament"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "town"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "user"');
    }
}
