<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260418153629 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE matches (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score1 INT DEFAULT NULL, score2 INT DEFAULT NULL, round INT NOT NULL, player1_id INT DEFAULT NULL, player2_id INT DEFAULT NULL, tournament_id INT NOT NULL, winner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_62615BAC0990423 ON matches (player1_id)');
        $this->addSql('CREATE INDEX IDX_62615BAD22CABCD ON matches (player2_id)');
        $this->addSql('CREATE INDEX IDX_62615BA33D1A3E7 ON matches (tournament_id)');
        $this->addSql('CREATE INDEX IDX_62615BA5DFCD4B8 ON matches (winner_id)');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT FK_62615BAC0990423 FOREIGN KEY (player1_id) REFERENCES registered (id)');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT FK_62615BAD22CABCD FOREIGN KEY (player2_id) REFERENCES registered (id)');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT FK_62615BA33D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT FK_62615BA5DFCD4B8 FOREIGN KEY (winner_id) REFERENCES registered (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE matches DROP CONSTRAINT FK_62615BAC0990423');
        $this->addSql('ALTER TABLE matches DROP CONSTRAINT FK_62615BAD22CABCD');
        $this->addSql('ALTER TABLE matches DROP CONSTRAINT FK_62615BA33D1A3E7');
        $this->addSql('ALTER TABLE matches DROP CONSTRAINT FK_62615BA5DFCD4B8');
        $this->addSql('DROP TABLE matches');
    }
}
